// Angular/src/app/table/table.component.ts
import { Component, EventEmitter, Input, OnChanges, Output, SimpleChanges } from '@angular/core';

@Component({
  selector: 'body-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class TableComponent implements OnChanges {
  @Input() columns: string[] = [];
  @Input() data: any[] = [];
  @Output() rowClickEvent = new EventEmitter();

  rows: any[] = [];

  constructor() { }

  ngOnChanges(changes: SimpleChanges): void {
    this.rows = this.formatData(changes['data'].currentValue);
  }

  formatData(data: any[]): any[] {
    return data.map((item: any) => {
      const values = Object.values(item);
      return values.map((value: any) => {
        return typeof value === 'boolean'
          ? (value ? "Có" : "Không")
          : value
      });
    });
  }

  onRowClick(id: any): void {
    this.rowClickEvent.emit(id);
  }
}

<table class="w-full text-sm text-left text-gray-100">
  <thead class="text-xs text-gray-400 uppercase bg-gray-700">
    <tr>
      <th
        scope="col"
        class="px-6 py-3 text-center"
        *ngFor="let name of columns"
      >
        {{ name }}
      </th>
    </tr>
  </thead>
  <tbody>
    <tr
      class="border-b bg-gray-600 border-gray-700 hover:bg-gray-500"
      *ngFor="let row of rows"
      (click)="onRowClick(row[0])"
    >
      <td
        class="px-6 py-4 whitespace-normal text-center"
        *ngFor="let cell of row"
      >
        {{ cell }}
      </td>
    </tr>
  </tbody>
</table>

// AdminSite/src/components/common/table.jsx
import React from "react";

const Table = ({ columns, data, onRowClick }) => {
  if (!columns || columns.length <= 0 || !data || data.length <= 0) {
    return <></>;
  }

  return (
    <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          {columns.map((column, index) => {
            return (
              <th key={index} scope="col" className="px-6 py-3 text-center">
                {column}
              </th>
            );
          })}
        </tr>
      </thead>
      <tbody>
        {data.map((item, index) => {
          const values = Object.values(item);
          return (
            <tr
              key={index}
              onClick={() => onRowClick(item.id)}
              className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
            >
              {values.map((ele, index) => {
                return (
                  <td key={index} className="px-6 py-4 whitespace-normal text-center">
                    {typeof ele === "boolean" ? (ele ? "Có" : "Không") : ele}
                  </td>
                );
              })}
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};

export default Table;
