// AdminSite/src/components/common/pagination.jsx
import React from "react";

const Pagination = ({ current, total, onClick }) => {
  const rank = current / 5;
  let from = -2;

  if (rank === 0.2) {
    from = 0;
  } else if (rank === 0.4) {
    from = -1;
  }

  return (
    <nav aria-label="Page navigation example">
      <ul className="inline-flex items-center -space-x-px">
        {current > 1 && (
          <li>
            <button
              onClick={() => onClick(current - 1)}
              className="block py-2 px-3 ml-0 leading-tight text-gray-500 bg-white rounded-l-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
            >
              <span className="sr-only">Previous</span>
              <svg
                className="w-5 h-5"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"></path>
              </svg>
            </button>
          </li>
        )}
        {Array.from(
          [...Array(5)].fill(from),
          (value, index) => value + index + rank * 5
        ).map((element) => {
          const styledClass =
            element === current
              ? "z-10 text-blue-600 bg-blue-50 border-blue-300 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white"
              : "text-gray-500 bg-white border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white";
          return element - 1 >= total ? null : (
            <li key={element}>
              <button
                onClick={() => onClick(element)}
                className={"py-2 px-3 leading-tight border " + styledClass}
              >
                {element}
              </button>
            </li>
          );
        })}
        {total > current && (
          <li>
            <button
              onClick={() => onClick(current + 1)}
              className="block py-2 px-3 leading-tight text-gray-500 bg-white rounded-r-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
            >
              <span className="sr-only">Next</span>
              <svg
                className="w-5 h-5"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"></path>
              </svg>
            </button>
          </li>
        )}
      </ul>
    </nav>
  );
};

export default Pagination;

// Angular/src/app/pagination/pagination.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';

@Component({
  selector: 'table-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: ['./pagination.component.css'],
})
export class PaginationComponent implements OnChanges {
  @Input() current: number = 0;
  @Input() total: number = 0;
  @Output() pageClickEvent = new EventEmitter();

  pages: number[] = [];

  constructor() {}

  ngOnChanges(): void {
    this.calculateDisplayPages();
  }

  calculateDisplayPages(): void {
    const numberOfPage = 5;
    const rank = this.current / numberOfPage;
    let from = -2;

    if (rank === 0.2) {
      from = 0;
    } else if (rank === 0.4) {
      from = -1;
    }

    this.pages = Array.from(
      [...Array(numberOfPage)].fill(from),
      (value: number, index: number): number => value + index + rank * numberOfPage
    ).filter((value: number): boolean => value <= this.total);
  }

  onPageClicked(pageNumber: number): void {
    this.pageClickEvent.emit(pageNumber);
  }
}

<nav aria-label="Page navigation example">
  <ul class="inline-flex items-center -space-x-px">
    <li *ngIf="current > 1">
      <button
        (click)="onPageClicked(current - 1)"
        class="block py-2 px-3 ml-0 leading-tight text-gray-500 bg-gray-700 rounded-l-lg border border-slate-600 hover:bg-gray-500 hover:text-gray-800"
      >
        <span class="sr-only">Previous</span>
        <svg
          class="w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
          ></path>
        </svg>
      </button>
    </li>
    <li *ngFor="let page of pages">
      <button
      class="py-2 px-3 leading-tight border"
      (click)="onPageClicked(page)"
      [ngClass]="page === current
        ? 'bg-gray-600 text-white border-slate-500 z-10'
        : 'bg-gray-700 text-gray-400 border-slate-600 hover:bg-gray-500 hover:text-gray-800'"
      >
        {{page}}
      </button>
    </li>
    <li *ngIf="total > current">
      <button
        (click)="onPageClicked(current + 1)"
        class="block py-2 px-3 leading-tight text-gray-500 bg-gray-700 rounded-r-lg border border-slate-600 hover:bg-gray-500 hover:text-gray-800"
      >
        <span class="sr-only">Next</span>
        <svg
          class="w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"></path>
        </svg>
      </button>
    </li>
  </ul>
</nav>
