// Angular/src/app/categories/category-form/category-form.component.ts
import { Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges } from '@angular/core';
import { NgForm } from '@angular/forms';
import { CREATE_FORM_TYPE, EDIT_FORM_TYPE } from 'src/constants/variables';
import { Category } from '../category.model';

@Component({
  selector: 'category-form',
  templateUrl: './category-form.component.html',
  styleUrls: ['./category-form.component.css'],
})
export class CategoryFormComponent implements OnInit, OnChanges {
  @Input() type: string = CREATE_FORM_TYPE;
  @Input() formData: Category | undefined;

  category!: Category;
  isEdit!: boolean;

  @Output() onSubmitEvent = new EventEmitter();

  constructor() {}

  ngOnInit(): void {
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.isEdit = this.type === EDIT_FORM_TYPE;

    if (this.isEdit)
      this.category = changes['formData'].currentValue;
    else
      this.category = new Category();

  }

  onSubmit(formData: NgForm): void {
    const emitData: any = {
      valid: formData.valid,
      data: formData.value,
    };

    this.onSubmitEvent.emit(emitData);
  }
}

<div class="flex-1 mb-16">
  <form
    class="mx-4 mt-6"
    #categoryForm="ngForm"
    (submit)="onSubmit(categoryForm)"
  >
    <input
      id="id"
      name="id"
      type="number"
      [hidden]="true"
      *ngIf="isEdit"
      [ngModel]="category.id"
    />

    <div class="relative z-0 w-full mb-6 group">
      <input
        id="name"
        type="text"
        name="name"
        placeholder=" "
        class="block py-2.5 px-0 w-full text-sm text-gray-50 bg-transparent border-0 border-b-2 border-gray-400 appearance-none focus:outline-none focus:ring-0 focus:border-gray-300 peer"
        [(ngModel)]="category.name"
        #inputName="ngModel"
        required
      />
      <label
        htmlFor="name"
        class="peer-focus:font-medium absolute text-sm text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-gray-200 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
      >
        Tên thể loại
      </label>
      <span
        class="peer-focus:font-medium text-sm text-red-600"
        role="alert"
        *ngIf="
          !inputName.valid && (!inputName.pristine || categoryForm.submitted)
        "
      >
        Tên thể loại là trường bắt buộc
      </span>
    </div>
    <div class="relative z-0 w-full mb-6 group">
      <input
        id="displayName"
        type="text"
        name="displayName"
        placeholder=" "
        class="block py-2.5 px-0 w-full text-sm text-gray-50 bg-transparent border-0 border-b-2 border-gray-400 appearance-none focus:outline-none focus:ring-0 focus:border-gray-300 peer"
        [(ngModel)]="category.displayName"
        #inputDisplayName="ngModel"
        required
        minlength="5"
      />
      <label
        htmlFor="displayName"
        class="peer-focus:font-medium absolute text-sm text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-gray-200 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
      >
        Hiển thị dưới tên
      </label>
      <span
        class="peer-focus:font-medium text-sm text-red-600"
        role="alert"
        *ngIf="
          !inputDisplayName.valid &&
          (!inputDisplayName.pristine || categoryForm.submitted)
        "
      >
        Tên hiển thị là trường bắt buộc và phải có tối thiểu 5 ký tự
      </span>
    </div>
    <div class="relative z-0 w-full mb-6 group">
      <input
        id="description"
        type="text"
        name="description"
        placeholder=" "
        class="block py-2.5 px-0 w-full text-sm text-gray-50 bg-transparent border-0 border-b-2 border-gray-400 appearance-none focus:outline-none focus:ring-0 focus:border-gray-300 peer"
        [(ngModel)]="category.description"
        #inputDescription="ngModel"
        required
        minlength="10"
      />
      <label
        htmlFor="description"
        class="peer-focus:font-medium absolute text-sm text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-gray-200 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
      >
        Mô tả
      </label>
      <span
        class="peer-focus:font-medium text-sm text-red-600"
        role="alert"
        *ngIf="
          !inputDescription.valid &&
          (!inputDescription.pristine || categoryForm.submitted)
        "
      >
        Mô tả là trường bắt buộc và phải có tối thiểu 10 ký tự
      </span>
    </div>
    <div class="flex justify-end">
      <button
        type="submit"
        class="mr-4 text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
      >
        {{isEdit ? "Cập nhật" : "Tạo mới"}}
      </button>
    </div>
  </form>
</div>

// AdminSite/src/components/form/category-form.jsx
import React from "react";
import { EDIT_FORM_TYPE } from "../../constants/variables";
import { useForm } from "react-hook-form";

const CategoryForm = ({ type, handleSubmitForm, item = null }) => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();
  return (
    <>
      <form className="mx-4 mt-6" onSubmit={handleSubmit(handleSubmitForm)}>
        {type === EDIT_FORM_TYPE && (
          <input
            id="id"
            type="number"
            hidden={true}
            defaultValue={item ? item.id : 0}
            {...register("id")}
          />
        )}

        <div className="relative z-0 w-full mb-6 group">
          <input
            id="name"
            type="text"
            name="category_name"
            placeholder=" "
            defaultValue={item ? item.name : ""}
            className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
            {...register("name", {
              required: {
                value: true,
                message: "Tên thể loại không được để trống",
              },
              minLength: {
                value: 5,
                message: "Tên thể loại phải có tối thiểu 5 ký tự",
              },
            })}
          />
          <label
            htmlFor="category_name"
            className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
          >
            Tên thể loại
          </label>
          {errors.name && (errors.name.type === "required" || "minLength") && (
            <span
              className="peer-focus:font-medium text-sm text-red-500"
              role="alert"
            >
              {errors.name.message}
            </span>
          )}
        </div>
        <div className="relative z-0 w-full mb-6 group">
          <input
            id="displayName"
            type="text"
            name="display_name"
            placeholder=" "
            defaultValue={item ? item.displayName : ""}
            className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
            {...register("displayName", {
              required: {
                value: true,
                message: "Tên hiển thị không được để trống",
              },
              minLength: {
                value: 10,
                message: "Tên hiển thị phải có tối thiểu 10 ký tự",
              },
            })}
          />
          <label
            htmlFor="display_name"
            className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
          >
            Hiển thị dưới tên
          </label>
          {errors.displayName &&
            (errors.displayName.type === "required" || "minLength") && (
              <span
                className="peer-focus:font-medium text-sm text-red-500"
                role="alert"
              >
                {errors.displayName.message}
              </span>
            )}
        </div>
        <div className="relative z-0 w-full mb-6 group">
          <input
            id="description"
            type="text"
            name="description"
            placeholder=" "
            defaultValue={item ? item.description : ""}
            className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
            {...register("description", {
              required: {
                value: true,
                message: "Mô tả không được để trống",
              },
              minLength: {
                value: 20,
                message: "Mô tả phải có tối thiểu 20 ký tự",
              },
            })}
          />
          <label
            htmlFor="description"
            className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
          >
            Mô tả
          </label>
          {errors.description &&
            (errors.description.type === "required" || "minLength") && (
              <span
                className="peer-focus:font-medium text-sm text-red-500"
                role="alert"
              >
                {errors.description.message}
              </span>
            )}
        </div>
        <div className="flex justify-end">
          <button
            type="submit"
            className="mr-4 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            {type === EDIT_FORM_TYPE ? "Cập nhật" : "Tạo mới"}
          </button>
        </div>
      </form>
    </>
  );
};

export default CategoryForm;
